### ISSUE TITLE
关于数据集的一些问题

### ISSUE THREAD

**Issue by ykding666** [Titor99/SC-ReID#2]
这是一篇很不错的工作，感谢作者公布了源码。
但是在阅读源码的过程中，我我发现总共使用到了三种数据：RGB,Mask（SCHP），face。第二种比较好获得，利用schp批量处理可以得到，但是第三个face信息的图片，我想知道您是怎么处理获得的，如果有可能，可以上传PRCC,LTCC,VC等完整的处理过的数据集吗，要不然可能难以复现结果，谢谢！

**Comment by Titor99** [comment]
感谢您的关注，在SC-ReID项目中行人头部区域图像是通过hp图（Mask图）得出的，具体而言取了hp图中的头部区域像素（包括面部和头发区域）最左、最右、最上和最下而形成的矩形框。现在训练数据集已开源，在readme中已经添加百度网楼盘链接，您可以进行查看和下载。

**Comment by ykding666** [comment]
太感谢了，这对我的研究帮助很大。如果有可能的话，可以分享一下处理头部区域头像的源码吗，我自己尝试了几次没有成功，谢谢。我自己也弄出来了，感谢，这样后续在其他数据集上也可以用的了

**Comment by ykding666** [comment]
还有个问题想跟您探讨下，就是数据集中有部分图像没有face和hair。导致head的那个数据集和rgb，mask的数量不一样。这个不仅是出现在训练集train是，query里也有这种问题，这样会导致最后test集缺少的一个问题，我看到您数据集预处理也是忽略了这部分内容。

![123](https://github.com/user-attachments/assets/dc884e01-d220-4405-91c0-e97ccf9ca3ea)

**Comment by Titor99** [comment]
确实有部分图像是没有头部区域像素，但是只有训练数据集需要额外的mask图和head图，而测试集是不需要的。

**Comment by ykding666** [comment]
您好，我又试着复现了一下，无法复现成功，请问您上传GitHub之后是有检查过代码是吗。报错的原因的dataset样本为0.直接跳过了train代码里120行的for循环
![微信截图_20241123224614](https://github.com/user-attachments/assets/b026d2e9-4e81-4a92-b80e-4ba4c41a1734)

**Comment by ykding666** [comment]
上面报错的原因找到了，是数据集里的三个文件夹里的，query，gallery，train不太一致。但是在训练的过程中发现了一个新问题，就算test-loader里面的batch-size设置的是1，有什么特殊的含义吗，我设置大一点可以吗。我设置32了，可以正常跑通的，但是发现，推理的结果只有一个结果，这个看起来是只有换衣场景下的结果吗

**Comment by Titor99** [comment]
可以的，我的wx：pmwuzhiyue1111
至于推理部分的代码问题，我是参照了https://github.com/shuxjweb/pixel_sampling/blob/main/engine/inference.py这个代码来写，我的理解他这样写是在测试的时候去掉同一个摄像头下同一个人的数据，以此来保证gallery里面都是更换过服装的。至于用CAL的方法测得比较低，其他的数据集也存在这个问题吗？
